### PR TITLE
FIXED: Readme and acronyms

### PR DESCRIPTION
**Pull request by stephengade**

### CODE REVIEW

**Comment by kaf-lamed-beyt** [comment]
I thought I had merged this already.

**Comment by kaf-lamed-beyt** [comment]
@stephengade I think this is a duplicate PR, no?

**Comment by stephengade** [comment]
I had already sent the PR but I keep seeing the pop-up notification to send pull requests again. Kindly close it, I am pushing something soon, should override whatever that's not updated

**Comment by kaf-lamed-beyt** [comment]
Alright then

**Pull request closed without merging**
